// Code generated by MockGen. DO NOT EDIT.
// Source: sign_profile_service.go

// Package services is a generated GoMock package.
package services

import (
	domain "demo-signserver/internal/repository/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSignProfileServiceInterface is a mock of SignProfileServiceInterface interface.
type MockSignProfileServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSignProfileServiceInterfaceMockRecorder
}

// MockSignProfileServiceInterfaceMockRecorder is the mock recorder for MockSignProfileServiceInterface.
type MockSignProfileServiceInterfaceMockRecorder struct {
	mock *MockSignProfileServiceInterface
}

// NewMockSignProfileServiceInterface creates a new mock instance.
func NewMockSignProfileServiceInterface(ctrl *gomock.Controller) *MockSignProfileServiceInterface {
	mock := &MockSignProfileServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSignProfileServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignProfileServiceInterface) EXPECT() *MockSignProfileServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockSignProfileServiceInterface) CreateProfile(profile *domain.SignerProfile) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", profile)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockSignProfileServiceInterfaceMockRecorder) CreateProfile(profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockSignProfileServiceInterface)(nil).CreateProfile), profile)
}

// GetProfileByID mocks base method.
func (m *MockSignProfileServiceInterface) GetProfileByID(ID string) (*domain.SignerProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByID", ID)
	ret0, _ := ret[0].(*domain.SignerProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByID indicates an expected call of GetProfileByID.
func (mr *MockSignProfileServiceInterfaceMockRecorder) GetProfileByID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByID", reflect.TypeOf((*MockSignProfileServiceInterface)(nil).GetProfileByID), ID)
}

// UpdateProfile mocks base method.
func (m *MockSignProfileServiceInterface) UpdateProfile(ID string, profile *domain.SignerProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ID, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockSignProfileServiceInterfaceMockRecorder) UpdateProfile(ID, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockSignProfileServiceInterface)(nil).UpdateProfile), ID, profile)
}
